# Generated by Django 5.0.3 on 2024-03-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewebApp', '0002_manager_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deatails',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
    ]
