# Generated by Django 5.0.3 on 2024-04-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewebApp', '0003_rename_deatails_order_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='section',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
