# Generated by Django 5.0.3 on 2024-04-01 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewebApp', '0004_alter_employee_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ewebApp.manager'),
        ),
    ]
