# Generated by Django 5.0.3 on 2024-04-03 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewebApp', '0010_customer_email_customer_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
