# Generated by Django 5.0.3 on 2024-04-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewebApp', '0011_rename_phone_no_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ewebApp.customer'),
        ),
    ]
