# Generated by Django 5.0.3 on 2024-04-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewebApp', '0012_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('OnGoing', 'OnGoing'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
    ]
