# Generated by Django 5.0.3 on 2024-04-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewebApp', '0013_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
