# Generated by Django 5.0.3 on 2024-04-04 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ewebApp', '0015_order_progress_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
